FROM almalinux:9

LABEL org.opencontainers.image.authors="pdowler.cadc@gmail.com"

## copied from docker-base.git/cadc-java/Dockerfile ##
RUN groupadd --gid 8675309 opencadc \
    && useradd --uid 8675309 --home-dir / --shell /sbin/nologin \
        --no-create-home --no-user-group --no-log-init opencadc

# install repos
RUN  dnf -y install epel-release
RUN  dnf -y install 'dnf-command(config-manager)'
RUN dnf config-manager --add-repo "https://storage-ci.web.cern.ch/storage-ci/eos/diopside/tag/testing/el-9/x86_64/"
RUN echo "gpgcheck=1" >> /etc/yum.repos.d/storage-ci.web.cern.ch_storage-ci_eos_diopside_tag_testing_el-9_x86_64_.repo
RUN dnf config-manager --add-repo "https://storage-ci.web.cern.ch/storage-ci/eos/diopside-depend/el-9/x86_64/"
RUN echo "gpgcheck=1" >> /etc/yum.repos.d/storage-ci.web.cern.ch_storage-ci_eos_diopside-depend_el-9_x86_64_.repo
RUN cd /tmp && curl -O -J https://storage-ci.web.cern.ch/storage-ci/storageci.key && rpm --import /tmp/storageci.key

# install required software
RUN dnf install -y java-21-openjdk-headless ca-certificates sudo which nmap-ncat \
    && dnf install -y eos-client \
    && dnf clean all

## the rest is mainly copied from docker-base.git/cadc-java/Dockerfile ##

# system settings and permissions
COPY tantar-eos/nofiles.conf /etc/security/limits.d/
COPY tantar-eos/opencadc-sudo-perms /etc/sudoers.d/

RUN chgrp opencadc /etc/pki/ca-trust/source/anchors \
    && chmod 775 /etc/pki/ca-trust/source/anchors \
    && chmod 440 /etc/sudoers.d/opencadc-sudo-perms

## see https://bugzilla.redhat.com/show_bug.cgi?id=1773148
RUN touch /etc/sudo.conf && echo "Set disable_coredump false" > /etc/sudo.conf

# JVM settings
ENV JAVA_OPTS="-Xms512m -Xmx2048m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -XX:OnError='cat hs_err_pid%p.log'"

RUN mkdir /.ssl && chown opencadc:opencadc /.ssl && chmod 700 /.ssl

COPY tantar-eos/cadc-java-init /usr/bin/cadc-java-init

ENTRYPOINT ["/usr/bin/cadc-java-init"]

ADD build/distributions/tantar.tar /

CMD ["/tantar/bin/tantar"]
