name: Java CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
#    - name: build and test storage-inventory-dm
#      run: cd storage-inventory-dm && ../gradlew --info clean build xslt
      
    - name: build and test cadc-inventory
      run: cd cadc-inventory && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-inventory-db
      run: cd cadc-inventory-db && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-inventory-util
      run: cd cadc-inventory-util && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-inventory-server
      run: cd cadc-inventory-server && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-storage-adapter
      run: cd cadc-storage-adapter && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-storage-adapter-test
      run: cd cadc-storage-adapter-test && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-storage-adapter-fs
      run: cd cadc-storage-adapter-fs && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-storage-adapter-eos
      run: cd cadc-storage-adapter-eos && ../gradlew --info clean build javadoc checkstyleMain install

#    - name: build and test cadc-storage-adapter-s3
#      run: cd cadc-storage-adapter-s3 && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-storage-adapter-swift
      run: cd cadc-storage-adapter-swift && ../gradlew --info clean build javadoc checkstyleMain install

    - name: java build -- baldur
      run: cd baldur && ../gradlew --info clean build javadoc checkstyleMain

    - name: java build -- critwall 
      run: cd critwall && ../gradlew --info clean build javadoc checkstyleMain
      
    - name: java build -- fenwick
      run: cd fenwick && ../gradlew --info clean build javadoc checkstyleMain
      
    - name: java build -- minoc 
      run: cd minoc && ../gradlew --info clean build javadoc checkstyleMain
      
    - name: java build -- luskan
      run: cd luskan && ../gradlew --info clean build javadoc checkstyleMain
      
    - name: java build -- raven
      run: cd raven && ../gradlew --info clean build javadoc checkstyleMain

    - name: java build -- ratik
      run: cd ratik && ../gradlew --info clean build javadoc checkstyleMain

    - name: java build -- vault
      run: cd vault && ../gradlew --info clean build javadoc checkstyleMain

    - name: java build -- ringhold
      run: cd ringhold && ../gradlew --info clean build javadoc checkstyleMain
      
    - name: java build -- data
      run: cd compat-api/data && ../../gradlew --info clean build javadoc checkstyleMain

